### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jalemanyf** [srcnalt/OpenAI-Unity#3] opened 2023-01-14 18:48 UTC
I followed all the steps but when I push the button to send the text I always receive this error message:

NullReferenceException: Object reference not set to an instance of an object
OpenAI.ChatGPT.SendReply () (at Assets/Samples/OpenAI Unity/0.1.0/ChatGPT/ChatGPT.cs:41)

I have checked all the rederences in the editor ( the ChatGPT publics ) and all are correct.

I'm using Unity 2021.3.0f1 on a Mac.

Any help is welcome. Thanks!

**Comment by srcnalt** [comment] 2023-01-14 19:25
Hi @jalemanyf,

The line mentioned in the error message is `textArea.text = completionResponse.Choices[0].Text;`
In this case, either the `textArea` field is not set in the `ChatGPT` component, or the `Choices` array is empty. In the latter case, OpenAI did not send an empty response, which I never faced. So I suppose it's that the UI reference is missing.

**Comment by jalemanyf** [comment] 2023-01-15 12:18
Hi, @srcnalt , 

Thanks for your quick response ;)

I also supposed the same thing ( the UI reference is missing ) but, as I told you, I have checked all the references in the editor and all are correct, including the textArea.text.

I have debbuged the line and i attach an image. As you can see the textArea as value ( in green ) but the problem is on the completionResponse. It is null! :(

On the debug I have checked also thar my api_key and organization key are correct on the auth.json and they are correct and readed before the call to the API...

Any suggestion?

Best Regards,

Josep Alemany

![Captura de pantalla 2023-01-15 a las 13 07 00](https://user-images.githubusercontent.com/1040497/212539691-a5b53c37-27b7-4047-aad7-4d9893740f43.png)

**Comment by jalemanyf** [comment] 2023-01-15 12:54
I have come in on the openAI page to read more abaout the API ( my first idea was to make a simple, simple test with an API REST client ) but I have a surprise... it seems the service is disabled at the moment. 

For these reason I'm not receiving any response... 

I will try it again when it is working, it seems is a backend problem.

Thanks!

![Captura de pantalla 2023-01-15 a las 13 39 15](https://user-images.githubusercontent.com/1040497/212541697-64dc1b80-53d1-4cca-bafe-c78bfdc10859.png)

**Comment by srcnalt** [comment] 2023-01-15 13:35
Hi @jalemanyf,

I do not have error messaging covered in the requests just yet, all the fields of the response null means it could not cast the JSON correctly, which most probably was the error message. I'll create a task for that so I get that covered, in any case, a response error comes from OpenAI I can give this info to the user.

You can debug the DispatchRequest method to see the actual JSON you receive.

**Comment by COSMYIN90** [comment] 2023-01-17 09:21
Hello, @jalemanyf I think is not a server side issue I have the same problem on Windows when I try to make an API Call from ChatGPT Scene.Please see the attachment. 

![2023-01-17_11h18_26](https://user-images.githubusercontent.com/45771720/212858999-8dce5219-f5ee-4caa-83ad-5718ea8e8e89.png)

**Comment by devzhuchuanbo** [comment] 2023-01-17 09:42
I got this problem too. completionResponse.Choices[0] is null.

**Comment by srcnalt** [comment] 2023-01-17 20:43
Hi @COSMYIN90, @jalemanyf,

I just released v0.1.1 #5 which has error handling. This should at least help you see what the problem is.

**Comment by brunno0204** [comment] 2023-01-19 12:14
![image](https://user-images.githubusercontent.com/22185259/213440281-3bdb947d-6739-46c3-bca5-c15a962a4b1e.png)

@COSMYIN90 @srcnalt I'm having the same error as COSMYIN90, do you know how to fix that?

**Comment by srcnalt** [comment] 2023-01-19 12:30
Hi @brunno0204 @COSMYIN90 I just realized the issue is happening during JSON parsing in the `Configuration.cs` script. Which means something with the `auth.json` might be wrong. Could you check your `/.openai/auth.json` file to if it is a valid JSON?

**Comment by brunno0204** [comment] 2023-01-19 14:43
![image](https://user-images.githubusercontent.com/22185259/213471492-ed54d1c5-e312-4c3d-a8cb-ed9d4ee7028e.png)
![image](https://user-images.githubusercontent.com/22185259/213471883-d032b914-b896-49ed-ae89-acfac79a003c.png)
It looks ok for me...

**Comment by brunno0204** [comment] 2023-01-19 15:01
![image](https://user-images.githubusercontent.com/22185259/213476461-60a76bdd-c81c-41c4-9638-6e726c0632a5.png)
did this and its working, and i think i'll stick with that as ill be using webgl

**Comment by srcnalt** [comment] 2023-01-19 16:42
@brunno0204 It has to be called `api_key` instead of `private_api_key` or any other word. You might as well keep the API key in your source code, but this poses danger.

**Comment by brunno0204** [comment] 2023-01-19 23:13
@srcnalt Hi! I was able to compile on WebGL, problem is, it's giving me errors when i try to interact with the API(the libc error on console), i suspect it has to do with threading not supported on webgl, do you know a workaround for this?
![image](https://user-images.githubusercontent.com/22185259/213582973-ac2c21ce-80ec-496a-a70d-bd5ccf5bc287.png)

**Comment by srcnalt** [comment] 2023-01-20 00:09
Hi @brunno0204, WebGL app cannot read your local files such auth.json
This project is not intended for production use, it might pose issues if your API key is compromised.

**Comment by brunno0204** [comment] 2023-01-20 00:15
@srcnalt on my last pic before this one ,i told ya i put the api key on the configurator.cs code, so thats not the problem really. And i really dont Care about the security of the key. I saw that on the openaiapi.cs theres multithread lib included. Do you think that is the culprit or might be something else?

**Comment by srcnalt** [comment] 2023-01-20 00:21
Probably since Tasks and async code are still a problem in Unity WebGL builds.

**Comment by brunno0204** [comment] 2023-01-20 00:29
I'll to replace them with unitask tomorrow and see what happens

**Comment by srcnalt** [comment] 2023-01-20 00:41
auth.json file check, json to data object field name mapping, and api_key as a required field brought in #6 closing the issue.

**Closed by srcnalt** 2023-01-20 00:41 UTC
